### PR TITLE
task: specify node version to reduce conflicts

### PR DESCRIPTION
**Pull request by colemars**
This project relies on a specific node version(s), but doesn't specify it anywhere - causing conflicts when contributors with older versions installed set up the env.

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
I've never needed to do this in a project before. Which versions won't it work on? Is there a way to find that information?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by colemars** [comment]
> Note that the file format changed significantly in npm v7 to track information that would have otherwise required looking in node_modules or the npm registry. Lockfiles generated by npm v7 will contain lockfileVersion: 2.
> 
> No version provided: an "ancient" shrinkwrap file from a version of npm prior to npm v5.
> 1: The lockfile version used by npm v5 and v6.
> 2: The lockfile version used by npm v7, which is backwards compatible to v1 lockfiles.
> 3: The lockfile version used by npm v7, without backwards compatibility affordances. This is used for the hidden lockfile at node_modules/.package-lock.json, and will likely be used in a future version of npm, once support for npm v6 is no longer relevant.
> 
https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion

So,

- v1 => npm v5 and v6.
- v2: => npm v7&v8, which is backwards compatible to v1 lockfiles.
- v3: => npm v7&v8 without backwards compatibility

and from https://nodejs.org/en/download/releases/

- Node v14 => npm v6
- Node v15&16 => npm v7
- Node v17+ => npm v8

Current Node version is 18, active LTS is 16, and maintenance LTS is 14.

Anybody installing your project with a version of node outside of 15/16 will have a different lockfile than the project, which has the potential for changing how the project runs for them. And since v14 is still in lts and v18 is coming down the pipeline (so we can assume there are going to be plenty of people using all 3) we should specify the version of node (and as a result, npm) we use so that us in the future / other contributors to the project don't encounter any bugs relating to an altered lockfile, and also PRs won't contain the altered lockfiles.

I specified `lts` to target `Node@v16` but it may be better to specify 16 outright depending on how non-backwards compatible npm v8 is...

Or just use yarn😜 

Though it's also generally best practice to specify your node version via a `nvm` or `nodeversion` file if your project contains any node scripts.

In addition to this PR, the contributing docs should be updated to let people know that `nvm` or `fnm` is a required dependency and to run `nvm use` when setting up the proj

**Comment by EmmaDawsonDev** [comment]
Ok, I think this is something I need more time to look into as it's not something I'm familiar with and don't want to cause more problems than necessary. I don't have node version manager because I'm using windows and it's not available on windows. I don't want to lock myself out of my own project next time I update node/npm. I also want this project to be something that is easy for beginners to open source to contribute to and I worry that adding extra requirements like this would be offputting. I know that such requirements have put me off contributing to projects in the past.

**Comment by MarkusEicher** [comment]
> Hi folks. I agree with Emma that this kind of dependency and version hell is driving people away from contributing to the project. Nontheless I dare to add a few questions to this. If you consider them as too far from the topic, please ignore them and proceed. I am a newbie and I just forked and cloned this repo in wich I'm very interested. The following is concerning me and I am already on Stackoverflow to find out what it actually means for me.

> I use Node v16.17.0 and npm v8.19.1. After running npm install i receive the following output. I'm only concerned about the boldened part in this message:


$ npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

color-palette-combos@0.1.0 prepare
husky install

husky - Git hooks installed

added 1489 packages, and audited 1490 packages in 23s

212 packages are looking for funding
  run `npm fund` for details

### 7 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 8.15.0 -> 8.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.1>
npm notice Run `npm install -g npm@8.19.1` to update!
npm notice

___

> I then thought to try the npm audit fix command to fix the issues without braking changes so I left the --force switch alone. This was the output after this command:


$ npm audit fix

changed 1 package, and audited 1490 packages in 18s

212 packages are looking for funding
  run `npm fund` for details

npm audit report

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@2.1.3, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          node_modules/react-scripts

### 6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

___

> There are still 6 high severe vulnerabilities in the dependencies left, but I won't use npm audit fix --force at this point. On Stackoverflow I was advised to user npm ci too. I executed this command and the result was the same as when using npm audit fix. 

$ npm ci
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

color-palette-combos@0.1.0 prepare
husky install

husky - Git hooks installed

added 1489 packages, and audited 1490 packages in 47s

212 packages are looking for funding
  run `npm fund` for details

### 6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

___

> As mentioned before, this is only informational. I will use the project as it is now. After checking out to a new branch Development i ran npm start. This was the output i got:


$ npm start

color-palette-combos@0.1.0 start
react-scripts start

(node:6140) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:6140) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view color-palette-combos in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.0.143:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully

___

> The application is running smoothly on localhost:3000. Good enough for me to dig in the code. I only though I will post this here, because it might influence your decision of merging @colemars PR.
> 
> Have a good time.
> 
> Greetings Markus
>

**Comment by EmmaDawsonDev** [comment]
Thanks for the extra information @MarkusEicher I really need to learn more about what this all means myself 😬

**Comment by MarkusEicher** [comment]
Hi Emma.

Sorry, if my comment was a little too extensive. 😜 I didn't want stirring it up or build confusion. The reason I commented this PR is, that Node.js has a system to track project dependencies which will be part of the project and tracked by Git. In my fork these dependencies may vary from the ones in someone others, depending on the version of Node.js in use. I do not already understand this matter enough, but it bothers me that in these dependencies there seem to be high severity vulnerabilities. If I now remove or mitigate them, then these will be reflected in my repo and occasionally be merged in the production branch. This might lead to problems for other contributors or users. This is not a problem of the code of this solution, but seems to be a thing to consider for all solutions using a certain version of Node.js. Sorry, I can't explain it better at this point. Don't worry too much about it. I will try to figure out what it's all about this issue, because I plan to learn and use Node.js for my projects too. If I find something helpful I will communicate it. Sorry for the flood, I promise to reduce the spam. 😎

**Comment by EmmaDawsonDev** [comment]
Oh no, don't worry about that. I'm really glad for your comment and all the details. It helps me to know what to focus on and improve too!

**Review by EmmaDawsonDev — APPROVED** [review]

**Pull request merged**
