### PR TITLE
Seperate Css into Module files

### PR DESCRIPTION
**Pull request by timo-tech19**
Created unique folders for each component containing both the .jsx and .module.css files.

### CODE REVIEW

**Comment by timo-tech19** [comment]
I noticed a certain className has been repeated and used in two separate components `.colorInputContainer`
`.colorInputContainer {
	position: relative;
}`
&&
`.colorInputContainer {
	display: flex;
	gap: 0.5rem;
	flex-wrap: wrap;
}
`
The className has been used in `App.jsx` on `line 87` and in `ColorInput.jsx` on `line 19`

**Review by EmmaDawsonDev — APPROVED** [review]
This looks great Timo! Thank you so much for your help!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Comment by EmmaDawsonDev** [comment]
> I noticed a certain className has been repeated and used in two separate components `.colorInputContainer` `.colorInputContainer { position: relative; }` && `.colorInputContainer { display: flex; gap: 0.5rem; flex-wrap: wrap; } ` The className has been used in `App.jsx` on `line 87` and in `ColorInput.jsx` on `line 19`

Oh, well spotted!! I hadn't noticed that at all. Did you want to update the one in App.js /App.css to something like colorInputSectionContainer as part of this PR or would you rather I do it once this PR is merged? 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by EmmaDawsonDev** [comment]
I'll merge it and fix the clashing names in a separate PR. Thanks so much for your help Timo!

**Pull request merged**
